print('hello.world!!!')
print(2+3)
print('Dia', 'Mês', 'Ano', sep='/')
print('ontem','hoje','Amanhã',sep='-')
print("B" , "n","n" ,"." , sep='a')

print(42000)
print(42,000)
print(42.000)
print(type(42000))
print(type(42.000))
print(type(42))

print("10" +"10")
print("10")
print(type("10"))

print(type('Esse e um string.') )
print(type("E esse  tambem e um string.") )
print(type(""" e esse tambem .""") )
print(type('''e mesmo esse...''') )

mensagem = "Nao contava com a minha astucia"
n= 2021
pi= 3.14159
print(mensagem)
print(n)
print(pi)
tipo = True
print(type(tipo))

print(81**0.5)

#Atribuição: = e Igualdade: ==

print('3**3**6')

altura=1.60
peso=58
imc= (peso)/ (altura**2)
print(imc)

nome=input("Digite o seu nome")
print(nome)